### ISSUE TITLE
Prepare Solidus Webhooks for Solidus 3.0

### ISSUE THREAD

**Issue by kennyadsl** [solidusio-contrib/solidus_webhooks#8]
Update this extension so that it works with Solidus 3.0 by making sure the specs pass.

**Comment by zabrador** [comment]
I can grab this one!

**Comment by zabrador** [comment]
It seems as though no changes are necessary here. All specs pass for all versions, and no deprecations are shown. I can create a PR for bumping `solidus_support` in the gemspec though if that would be helpful!

**Comment by seand7565** [comment]
@zabrador The Solidus Support bump would be great if you have time, but closing this issue as it looks like there's nothing to do. Thanks for looking into it! 🎉
